### ISSUE TITLE
_scaleStart must be greater than 0

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-confidenceSlider#46]
We're seeing a Javascript error when _scaleStart is set to 0 (like in the example.json).  This only happens when the user clicks submit _without first touching the slider handle_ with the handle set to 0.  This is fine if the user moves the handle to another number and back to 0 (or any other number), and then clicks submit.  adapt-contrib-slider does not seem to have this problem.

Suggest either allowing a 0 value or changing the example.json and plugin instructions.

**Javascript error**
sliderModel.js: this.get(...) is undefined

**Environment**
Adapt v5.7
Confidence Slider v3.0.0

**Comment by moloko** [comment]
I’ll try and take a look at this tomorrow

**Comment by moloko** [comment]
Due to lack of time I didn't manage to get very far with this, but here's what I have managed to discover:
- setting `_shouldRecordInteractions: false` in spoor - or `_recordInteraction: false` for the confidence slider component - stops the error from appearing
- the problem is basically down to `_userAnswer` not being set to a valid value until the learner actually interacts with the component which, in turn, I think is due to:
- `_selectedItem` not being set to a valid value (it's just an empty `object`) until the learner interacts with the component

What I haven't managed to figure out is why neither `_userAnswer` not `_selectedItem` are being set correctly - given that this component inherits a lot of code from adapt-contrib-slider it must be something to do with the one of the overrides in confidenceSliderModel.js (?) being set up wrong - or possibly executing at the wrong time.

**Comment by moloko** [comment]
Also just to note that adapt-contrib-slider does NOT have the same issue if you set `"_scaleStart": 0` for that component

**Comment by moloko** [comment]
wow I really thought this would be a fairly easy one to solve but it's SO not! Perhaps something to do with trying to debug at half seven on a friday with the best part of a bottle of wine in me ;-)

So far I have managed to figure out that at the point that `ConfidenceSliderModel.init` is called, `_selectedItem` is set correctly. 

But shortly after that it gets 'unset' again (same thing happens for Slider)... 

At some point during the render process for Slider, this property gets set back to the correct value - but, for some reason I just can't fathom, the same thing doesn't happen for Confidence Slider. 

So, when you click the submit button, `QuestionView` executes `SliderModel.storeUserAnswer` which tries to copy the value of  `_selectedItem` into `_userAnswer` - but at this point `_selectedItem` is just an empty object - so `_userAnswer` therefore ends up being set to `undefined` which of course means that `getResponse` will throw an error when called since it's trying to do `toString` on `_userAnswer` (which is `undefined`).

A very hacky fix would be to modify `Slider.getResponse` to return the value of `_scaleStart` if `_userAnswer` is `undefined` - but there must be a better solution than that!

I invoke @chris-steele as the in-house expert on confidence slider... go Chris!!

**Comment by tomgreenfield** [comment]
> At some point during the render process for Slider, this property gets set back to the correct value - but, for some reason I just can't fathom, the same thing doesn't happen for Confidence Slider.

Confidence Slider does properly set its `_selectedItem` from the inherited Slider call [here](https://github.com/adaptlearning/adapt-contrib-slider/blob/master/js/sliderView.js#L217) but the problem is it then does its own manual reset afterwards on line 94:
https://github.com/adaptlearning/adapt-contrib-confidenceSlider/blob/dc7d921fc1878160d9e8631d96686f3cfcfb5c4c/js/confidenceSliderView.js#L91-L97

**Comment by moloko** [comment]
and just to note that `ConfidenceSlider.onResetClicked` is being called via `QuestionView.checkIfResetOnRevisit` [here](https://github.com/adaptlearning/adapt_framework/blob/2b684d53a5349305d33d4868a124b786453b6583/src/core/js/views/questionView.js#L99-L105)

**Comment by chris-steele** [comment]
Picking this up now...

**Comment by chris-steele** [comment]
The essence of the problem is that adapt-contrib-slider sets a default item selection, but this is not respected by `restoreUserAnswers` and `resetUserAnswer`, so I've made an amendment which seems to work just fine.
